=== d-sarapaniuk/internet-lab-2-xml/customs.dtd
<!ELEMENT CustomsDeclarations (Entry*)>
<!ELEMENT Entry (Citizen, VisitCountry, AmountOfMoney, SpecialLuggage?)>

<!ELEMENT Citizen (FirstName, LastName, Patronymic?, NativeCountry)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Patronymic (#PCDATA)>
<!ELEMENT NativeCountry (#PCDATA)>

<!ELEMENT VisitCountry (#PCDATA)>

<!ELEMENT AmountOfMoney (#PCDATA)>

<!ELEMENT SpecialLuggage (Item*)>
<!ELEMENT Item (#PCDATA)>

=== d-sarapaniuk/internet-lab-2-xml/customs.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE CustomsDeclarations SYSTEM "customs.dtd">
<?xml-stylesheet type="text/css" href="customs.css"?>
<!-- <?xml-stylesheet type="text/xsl" href="customs.xsl"?> -->

<CustomsDeclarations>
    <Entry>
        <Citizen>
            <FirstName>Volodymyr</FirstName>
            <LastName>Osychniuk</LastName>
            <Patronymic>Serhiyovich</Patronymic>
            <NativeCountry>Ukraine</NativeCountry>
        </Citizen>
        <VisitCountry>France</VisitCountry>
        <AmountOfMoney>2500 euro</AmountOfMoney>
    </Entry>
    <Entry>
            <Citizen>
                <FirstName>Oksana</FirstName>
                <LastName>Demchiuk</LastName>
                <Patronymic>Andriivna</Patronymic>
                <NativeCountry>Ukraine</NativeCountry>
            </Citizen>
            <VisitCountry>Germany</VisitCountry>
            <AmountOfMoney>3000 euro</AmountOfMoney>
            <SpecialLuggage>
                <Item>Painting</Item>
                <Item>Silver Necklace</Item>
            </SpecialLuggage>
    </Entry>
    <Entry>
        <Citizen>
          <FirstName>John</FirstName>
          <LastName>Smith</LastName>
          <NativeCountry>United Kingdom</NativeCountry>
        </Citizen>
        <VisitCountry>Spain</VisitCountry>
        <AmountOfMoney>1800 euro</AmountOfMoney>
        <SpecialLuggage>
          <Item>Antique Watch</Item>
        </SpecialLuggage>
      </Entry>
</CustomsDeclarations>
